version: "2.1"

services:
  database:
    image: postgres:10.4
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

  nats:
    image: nats:latest

  test:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    command: ["npm", "run", "test:cov"]
    links:
     - database
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DATABASE: test
      NATS_URL: nats://nats:4222
    depends_on:
      - nats
      - database
