version: 2
jobs:
  build:
    working_directory: ~/myandela_server
    docker:
      - image: circleci/node:9.8.0
        environment:
          POSTGRES_USERNAME: postgres
          POSTGRES_DATABASE: test
          POSTGRES_PASSWORD: test
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          NATS_URL: nats://localhost:4222
      - image: sameersbn/postgresql:9.6-2
        environment:
          DB_USER: ci_user
          DB_PASS: test
          DB_NAME: test
      - image: nats:latest 

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn run test:coverage

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
